#!/usr/bin/env bash
# A Bash script that installs and configures Nginx on an Ubuntu server

apt-get update -y
apt-get install nginx -y
echo "Holberton School for the win!" > /var/www/html/index.html
service nginx start
